# Generated by Django 2.0.6 on 2018-06-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('artwork', models.ImageField(blank=True, upload_to='songlist')),
                ('release_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='songlist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('song_number', models.SlugField(max_length=10, unique=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True)),
                ('is_foreign_language', models.BooleanField(default=False)),
                ('album', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='songlist.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songlist.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songlist.Artist'),
        ),
    ]
