# Generated by Django 2.0.6 on 2018-06-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0002_auto_20180622_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
    ]
